defaut:
	g++ -o game InputManager.cpp InputManager.h Input.cpp Input.h Player.cpp Player.h Round.cpp Round.h Game.cpp Game.h APIHelper.cpp APIHelper.h Question.cpp Question.h QuestionManager.cpp QuestionManager.h Timer.cpp Timer.h TimeManager.cpp main.cpp TimeManager.h -lcurl -ljsoncpp -lwiringPi
clean:
	rm game
